# docker-compose.yml
version: '3.8'

services:
  sensor-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    restart: unless-stopped 

networks:
  smarthome-network:
    driver: bridge
    external: true
